name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  sqlite3: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
